server:
    port: 3025

spring:
    application:
        name: farm-service

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: none
        properties:
            dialect: dialect=org.hibernate.dialect.MySQL8Dialect

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/s10p31b302
        username: S10P31B302@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
        password: 4KocfCsPM9

#eureka
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k10b302.p.ssafy.io:30200/eureka
