server:
  port: 3020
spring:
  application:
    name: registry-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # eureka server port 변경시 defaultURL 명시
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/