server:
    port: ${SSE_PORT}

spring:
    application:
        name: sse-service

    jpa:
        show_sql: true
        hibernate:
            ddl-auto: none
        properties:
            dialect: dialect=org.hibernate.dialect.MySQL8Dialect

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PW}

#eureka
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${EUREKA_URL}
