server:
    port: 3021

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k10b302.p.ssafy.io:30200/eureka

spring:
    application:
        name: gateway-service

    cloud:
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
                corsConfigurations:
                    '[/**]':
                        allowedOriginPatterns: '*'
                        allow-credentials: true
                        allowedHeaders: '*'
                        exposedHeaders: '*'
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
            routes:
                - id: farm-service
                  uri: lb:FARM-SERVICE
                  predicates:
                      - Path=/api/farm-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=/api/farm-service/(?<segment>.*), /$\{segment}

                - id: sse-service
                  uri: lb:SSE-SERVICE
                  predicates:
                      - Path=/api/connection/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=/api/connection/(?<segment>.*), /$\{segment}

                - id: state-service
                  uri: lb:STATE-SERVICE
                  predicates:
                      - Path=/state-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=/api/state-service/(?<segment>.*), /$\{segment}

                - id: line-service
                  uri: lb:LINE-SERVICE
                  predicates:
                      - Path=/api/line-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=/api/line-service/(?<segment>.*), /$\{segment}
#        - id: sensor-service
#          uri: lb://SENSOR-SERVICE
#          predicates:
#            - Path=/sensor-service/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/sensor-service/(?<segment>.*), /$\{segment}
